version: "3"

services:
  api:
    build: api
    restart: unless-stopped
    ports: 
      - "3000:3000"
    depends_on:
      - db
  db:
    build: db
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
        - ./data:/data